# Format of prompt
format = """
[localhost:](green) \
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$java\
$gradle\
$kubernetes\
$directory\
$character
"""

# Inserts a blank line between shell prompts
add_newline = true

[aws]
disabled = true

[git_branch]
format = '[Git: $branch(:$remote_branch)]($style) '
style = 'bright-purple'

[git_commit]
disabled = false

[git_metrics]
disabled = false

[java]
format = '[Java:(${version}) ]($style)'

[gradle]
format = '[Gradle:(${version}) ]($style)'
style = 'dimmed yellow'

[kubernetes]
disabled = false
format = '[k8s:$context( \($namespace\))]($style)'
style = 'bright-cyan'

[directory]
truncation_length = 256
truncate_to_repo = false
style = 'bright-blue'
format = """

[$path]($style)[$read_only]($read_only_style)
"""

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'

